apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
      description: this will remove all preexisting files from 'resources'
  steps:
    - name: remove
      image: alpine:3
      env: 
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)  # FIXED: Changed {} to ()
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
          set -eu
          echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
          if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
            rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
            rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
            rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
          fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      type: string
      default: -v
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path) # FIXED: Changed 'workspace' to 'workspaces'
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)